name: idlebattle_server
description: Server for Idle Battle
version: 0.0.1
homepage: https://github.com/mauriciotogneri/idlebattle-server

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  shelf: ^1.3.1
  shelf_web_socket: ^1.0.2
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.1.11