package com.mauriciotogneri.idlebattle.types;

public enum OutputEvent
{
    ECHO,
    WAITING_PUBLIC,
    WAITING_PRIVATE,
    MATCH_READY,
    MATCH_STARTED,
    UNITS_LAUNCHED,
    MATCH_UPDATE,
    MATCH_FINISHED,
    INVALID_MATCH_ID,
    INVALID_PLAYER_NAME,
    INVALID_LANE_ID,
    INVALID_AMOUNT,
    PLAYER_DISCONNECTED
}
